FROM node:20-alpine

WORKDIR /app

# Dependências
COPY package*.json ./
COPY prisma ./prisma
RUN npm ci

# Código
COPY . .

# Gera Prisma Client
RUN npx prisma generate

EXPOSE 3000

CMD ["sh", "-c", "npx prisma migrate deploy && npm run start"]
